# Generated by Django 5.0.6 on 2024-05-23 12:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SAE201App", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jeu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=50)),
                ("editeur", models.CharField(max_length=50)),
                ("auteur", models.CharField(max_length=50)),
                ("photo", models.ImageField(null=True, upload_to="")),
                ("annee", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Joueur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("prenom", models.CharField(max_length=50)),
                ("mail", models.EmailField(max_length=50)),
                ("motdepasse", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[("PAR", "Particulier"), ("PRO", "Professionnel")],
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="Auteurs",
            new_name="Auteur",
        ),
        migrations.CreateModel(
            name="CommentaireJeu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("commentaire", models.TextField(max_length=5000)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "jeu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="SAE201App.jeu"
                    ),
                ),
                (
                    "joueur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SAE201App.joueur",
                    ),
                ),
            ],
        ),
    ]
