# Generated by Django 5.0.6 on 2024-05-23 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SAE201App", "0002_jeu_joueur_rename_auteurs_auteur_commentairejeu"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorieJeu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("descriptif", models.TextField(max_length=5000)),
            ],
        ),
        migrations.AddField(
            model_name="jeu",
            name="categorie",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="SAE201App.categoriejeu",
            ),
        ),
    ]
