# Generated by Django 5.0.6 on 2024-06-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SAE201App", "0003_categoriejeu_jeu_categorie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jeu",
            name="auteur",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="jeu",
            name="editeur",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="jeu",
            name="titre",
            field=models.CharField(max_length=100),
        ),
    ]
